ARG OPENAI_API_KEY 
FROM python:3.9-slim

COPY . .
EXPOSE 8501

RUN pip install --no-cache-dir  .

CMD streamlit run api/main.py --server.port=8501 --server.address=0.0.0.0 -- --openai_api_key ${OPENAI_API_KEY}

